CREATE TABLE IF NOT EXISTS user_role
(
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES user_info (user_id) ON DELETE CASCADE NOT NULL,
    role_id      BIGINT REFERENCES role (role_id) ON DELETE CASCADE      NOT NULL
);

INSERT INTO user_info (first_name, last_name, password_hash, email, nickname)
VALUES ('admin', 'admin', '$2a$10$1UTxbAJQ2I.HtwBWgirM/OJeBL2TAnD16cPFDZHSKgjnvA0ya21oi', 'admin@mail.com', 'admin');

INSERT INTO user_role(user_id, role_id)
VALUES(1, 1), (1, 2);